# Generated by Django 5.1.2 on 2025-02-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_editora"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name_plural": "Autores",
            },
        ),
    ]
