# Generated by Django 5.1.5 on 2025-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="email",
            field=models.EmailField(default="Teste", max_length=254),
            preserve_default=False,
        ),
    ]
