# Generated by Django 5.1.5 on 2025-02-02 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_editora_email"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="foto",
            field=models.ForeignKey(
                blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="uploader.image"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tipo_usuario",
            field=models.IntegerField(
                choices=[(1, "Cliente"), (2, "Vendedor"), (3, "Gerente")], default=1, verbose_name="User Type"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="editora",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Carrinho"), (2, "Finalizado"), (3, "Pago"), (4, "Entregue")], default=1
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.IntegerField(
                        choices=[
                            (1, "Cartão de Crédito"),
                            (2, "Cartão de Débito"),
                            (3, "PIX"),
                            (4, "Boleto"),
                            (5, "Transferência Bancária"),
                            (6, "Dinheiro"),
                            (7, "Outro"),
                        ],
                        default=1,
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="compras", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItensCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantidade", models.IntegerField(default=1)),
                ("preco", models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="core.compra"
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="itenscompra", to="core.livro"
                    ),
                ),
            ],
        ),
    ]
