# Generated by Django 5.1.5 on 2025-02-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_autor_options_editora_cidade_user_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Sem nome", max_length=255),
        ),
    ]

