# Generated by Django 5.1.5 on 2025-02-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_user_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.RemoveField(
            model_name="editora",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="user",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tipo_usuario",
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(default="NULL", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="editora",
            name="email",
            field=models.EmailField(default="NULL", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="Email", max_length=255, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indica que este usuário está ativo.", verbose_name="Usuário está ativo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Indica que este usuário pode acessar o Admin.",
                verbose_name="Usuário é da equipe",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, help_text="Username", max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(help_text="Passage ID", max_length=255, unique=True, verbose_name="passage_id"),
        ),
    ]
