# Generated by Django 5.1.5 on 2025-02-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_editora_cidade_alter_editora_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
